apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin-credentials
  namespace: jenkins
type: Opaque
stringData:
  username: "" #TODO: Add Jenkins admin username
  password: "" #TODO: Add Jenkins admin password
