apiVersion: v1
kind: Secret
metadata:
  name: jenkins-smtp-secret
  namespace: jenkins
type: Opaque
data:
  smtp-user: c2hpdmFtLnNoYXJtYS45NDI1MzNAZ21haWwuY29t
  smtp-password: b3NuciByZG52IHR4c3ogYmF5dQ==
