apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-node
  namespace: app
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - sourabh.techis.store
        - app.4.224.153.92.nip.io
      secretName: demo-node-tls
  rules:
    - host: sourabh.techis.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-node
                port:
                  name: http
    - host: app.4.224.153.92.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-node
                port:
                  name: http
