apiVersion: v1
kind: Secret
metadata:
  name: demo-node-secret
  namespace: app
  labels:
    app.kubernetes.io/name: demo-node
type: Opaque
data:
  API_KEY: ZGVtby1hcGkta2V5LXBsYWNlaG9sZGVy
  DB_PASSWORD: ZGVtby1kYi1wYXNzd29yZA==
  JWT_SECRET: ZGVtby1qd3Qtc2VjcmV0LWtleQ==
